///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String appIcons = 'assets/fonts/app_icons.ttf';
  static const String background = 'assets/images/background.png';
  static const String card = 'assets/images/card.png';
  static const String movie1 = 'assets/images/movies_list/movie_1.jpg';
  static const String movie10 = 'assets/images/movies_list/movie_10.jpg';
  static const String movie11 = 'assets/images/movies_list/movie_11.jpg';
  static const String movie12 = 'assets/images/movies_list/movie_12.jpg';
  static const String movie13 = 'assets/images/movies_list/movie_13.jpg';
  static const String movie14 = 'assets/images/movies_list/movie_14.jpg';
  static const String movie15 = 'assets/images/movies_list/movie_15.jpg';
  static const String movie16 = 'assets/images/movies_list/movie_16.jpg';
  static const String movie17 = 'assets/images/movies_list/movie_17.jpg';
  static const String movie18 = 'assets/images/movies_list/movie_18.jpg';
  static const String movie19 = 'assets/images/movies_list/movie_19.jpg';
  static const String movie2 = 'assets/images/movies_list/movie_2.jpg';
  static const String movie20 = 'assets/images/movies_list/movie_20.jpg';
  static const String movie3 = 'assets/images/movies_list/movie_3.jpg';
  static const String movie4 = 'assets/images/movies_list/movie_4.jpg';
  static const String movie5 = 'assets/images/movies_list/movie_5.jpg';
  static const String movie6 = 'assets/images/movies_list/movie_6.jpg';
  static const String movie7 = 'assets/images/movies_list/movie_7.jpg';
  static const String movie8 = 'assets/images/movies_list/movie_8.jpg';
  static const String movie9 = 'assets/images/movies_list/movie_9.jpg';
  static const String paypal = 'assets/images/paypal.png';
  static const String popcornCocacola = 'assets/images/popcorn_cocacola.png';
  static const String screen = 'assets/images/screen.png';

}
